apiVersion: v1
kind: Service
metadata:
  name: greetflow-api
spec:
  type: ClusterIP
  selector:
    app: greetflow-api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.apiPort }}
