{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: greetflow-openai
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.storeName | quote }}
    kind: ClusterSecretStore
  target:
    name: greetflow-openai
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.secretKey | quote }}
      remoteRef:
        key: {{ .Values.secrets.awsSecretName | quote }}
        property: {{ .Values.secrets.secretKey | quote }}
{{- end }}
