apiVersion: v1
kind: Service
metadata:
  name: greetflow-ui
spec:
  type: ClusterIP
  selector:
    app: greetflow-ui
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.uiPort }}
